development:
  adapter: postgresql
  database: specifi_development
  pool: 5

test:
  adapter: postgresql
  database: specifi_test
  pool: 5

production:
  adapter: postgresql
  database: specifi_development
  pool: 5